pixhawk:
  port: /dev/ttyUSB0
  baud: 115200
sys:
  recon_sysid: 150
  recon_compid: 1
  operator_sysid: 1
  operator_compid: 1
debug: true
log_dir: firelink/logs  
fire_confidence_threshold: 0.7
retry_count: 3
retry_backoff: [3,6,12]  # seconds
